dmake_version: 0.1
app_name: dmake-tutorial

env:
  default:
    variables:
      AMQP_URL: amqp://rabbitmq/dev

docker:
  base_image:
    name: dmake-tutorial-worker-base
    root_image: ubuntu:16.04
    raw_root_image: true
    install_scripts:
      - deploy/dependencies.sh

docker_links:
  - image_name: rabbitmq:3.7
    link_name: rabbitmq
    probe_ports:
      - 5672/tcp
    env:
      RABBITMQ_DEFAULT_VHOST: dev
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

services:
  - service_name: worker
    needed_links:
      - rabbitmq
    dev:
      entrypoint: deploy/entrypoint.sh
    config:
      docker_image:
        build:
          context: .
          dockerfile: deploy/Dockerfile
    tests:
      commands:
        - ./bin/worker_test
